//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "AbstractModelObserver.hh"

namespace Smart {

AbstractModelObserver::AbstractModelObserver(AbstractModel *model)
:	model(model)
{
	if(model != 0) {
		model->attach(this);
	}
}

AbstractModelObserver::~AbstractModelObserver()
{
	if(model != 0) {
		model->detach(this);
	}
}

} /* namespace Smart */
